WIP: Metal3 for Incubation
Nordix/toc pull request #1
Opened 2023-12-19 07:13 UTC by kashifest

!!! Just for review, please dont merge

2023-12-19 12:13 UTC, Rozzii requested changes
Just partial review I am continuing

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +TODO
just adding a comment here to make sure this does not stay as TODO

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +host management with Kubernetes. You can enroll your bare metal machines,
I suggest not using personal pronouns in technical document, I would use in the final doc things like: "user", or passive sentences or something along these lines.

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- New repository with iPXE firmware builder container utility-images
it is missing the link for the utility repo: https://github.com/metal3-io/utility-images

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +
Should we add the book here? https://book.metal3.io/

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- Added a user-guide in form of the Metal3Book
Link to the book https://book.metal3.io/

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +
We can make a screen shot from quay stats and upload it to nordix and link it from there same as for the sandbox if you's like to show the stats.

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +merging without proper reviews and tests. Dependabot has been implemented to
Dependabot has been adopted instead of "implemented"

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +of TLS 1.3 only.
We could mention that we are working on automated container signing infra

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +
Maybe we can put here clo monitor link

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +## Community size
I think just "Community" would be better header

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- Implemented support adding pre-provisining Network data for Ironic node [#1380](https://github.com/metal3-io/baremetal-operator/pull/1380)
- Explicit way to auto-detect disk image ChecksumType [#1480](https://github.com/metal3-io/baremetal-operator/pull/1480) 
- Support both Ironic and Inspector inventory formats [#1450](https://github.com/metal3-io/baremetal-operator/pull/1450)
- Expose FirmwareInterface in Node/BMC [#1441](https://github.com/metal3-io/baremetal-operator/pull/1441)
- API version negotiation [#1435](https://github.com/metal3-io/baremetal-operator/pull/1435)
- Ability to pass preprovisioningNetworkData to Ironic [#1380](https://github.com/metal3-io/baremetal-operator/pull/1380)

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
- Open up CAPM3 for any control plane provider [#1311](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1311)
- Add TLS configuration flags for CAPM3 [1041](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1041)
- Introduce ReconcileError with Transient and Terminal Error type [910](https://github.com/metal3-io/cluster-api-provider-metal3/pull/910)
- Add flags for configuring rate limits [959](https://github.com/metal3-io/cluster-api-provider-metal3/pull/959)

2023-12-19 12:13 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
- Implement CAPI IPAM contract support (https://github.com/metal3-io/cluster-api-provider-metal3/pull/769)
- Enable concurrency in metal3 controllers (https://github.com/metal3-io/cluster-api-provider-metal3/pull/884)
- Add explicit securitycontext to controllers (https://github.com/metal3-io/cluster-api-provider-metal3/pull/822)

2023-12-19 12:19 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
- Introduce separate go modules for e2e tests to allow them to be imported independently (https://github.com/metal3-io/cluster-api-provider-metal3/pull/800)

2023-12-19 12:21 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Add ability to use Ironic registry (not sure about the real name) instead of inspector
I have listed the related PR/Feature below

2023-12-19 12:21 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Ironic api version/compatibility discovery process from Dmitry
I have listed the feature above

2023-12-19 12:26 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
- Rework node reuse logic to handle corner cases in release-0.5 (https://github.com/metal3-io/cluster-api-provider-metal3/pull/425)

2023-12-19 12:28 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
- Add webhook readiness and health check (https://github.com/metal3-io/cluster-api-provider-metal3/pull/279)
- Add AGE column to metal3 CRDs (https://github.com/metal3-io/cluster-api-provider-metal3/pull/289)
- Automate releasing process with GitHub actions (https://github.com/metal3-io/cluster-api-provider-metal3/pull/308)

2023-12-19 12:34 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Something about Metal3DataTemplates and Metal3Data
Implement externally managed annotation (https://github.com/metal3-io/cluster-api-provider-metal3/pull/224)
- Add pivoting test based on the e2e test framework (https://github.com/metal3-io/cluster-api-provider-metal3/pull/232)
- Add internal logging mechanism for e2e test framework (https://github.com/metal3-io/cluster-api-provider-metal3/pull/259)
- Backport "Allow disable automated cleaning" (https://github.com/metal3-io/cluster-api-provider-metal3/pull/239)
- Use correct aliases for capm3 api (https://github.com/metal3-io/cluster-api-provider-metal3/pull/241)
- Add BMO inject-ca-from custom patching (https://github.com/metal3-io/cluster-api-provider-metal3/pull/223)

2023-12-19 12:34 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: Opening up CAPM3 to use it with non KCP control planes
Listed above

2023-12-19 12:44 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: IPv6 support?
- Add TLS configuration flags for IPAM (https://github.com/metal3-io/ip-address-manager/pull/248)
- Add flags for configuring rate limits (https://github.com/metal3-io/ip-address-manager/pull/238)
- Add support for mac (kustomize) (https://github.com/metal3-io/ip-address-manager/pull/267)
- Enable concurrency in ipam controllers (https://github.com/metal3-io/ip-address-manager/pull/213)
- add explicit securitycontexts to controller (https://github.com/metal3-io/ip-address-manager/pull/195)
- Default LeaderElectionResourceLock to leases (https://github.com/metal3-io/ip-address-manager/pull/85)
- Automate releasing process with GitHub actions (https://github.com/metal3-io/ip-address-manager/pull/66)
- Add AGE column to IPAM CRDs (https://github.com/metal3-io/ip-address-manager/pull/51)

2023-12-19 12:47 UTC, Rozzii commented on proposals/incubation/metal3.md
> +- TODO: IPv6 support?
I might have missed the IPv6 PR but I think the IPV6 support was present when the project entered sandbox

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +and Metal3 brings the baremetal implementation.
```suggestion
and Metal3 brings the bare metal implementation.
```

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +- Discover your hardware inventory
Did we merge the firmware update PR yet?

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +The Metal3 project went through many changes since its acceptance to incubation.
```suggestion
The Metal3 project has advanced a lot since its acceptance to incubation.
```
Or something like that. `went through many changes` is weird past tense

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +Repositories that have proved to be unmaintainable or lost their importance have
`Proved to be unmaintainable` is weird choice of words.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +As it stands today the project revolves around 4 core component plus a
```suggestion
As it stands today the project revolves around four core component plus a
```
Numbers less than 10 => words.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +Metal3 Community governance documents are located at [community](https://github.com/metal3-io/community)
Maybe make a list out of supporting repositories of the repos below.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +The website's source is located at [metal3-io.github.io](https://github.com/metal3-io/metal3-io.github.io)
Link the end result ie book here too.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +### Cluster-api-provider-metal3
Choose if you put in the repo name, ie. `cluster-api-provider-metal3` or use English `Cluster API Provider Metal3`.

Other repos have other mixed styles as well, mentioning only once here.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +- node reuse feature [#169](https://github.com/metal3-io/cluster-api-provider-metal3/pull/169)
```suggestion
- Node reuse feature [#169](https://github.com/metal3-io/cluster-api-provider-metal3/pull/169)
```
Please capitalize the first letters consistently, only mentioning once.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +- Custom PXE firmware building and deployment support  [#429](https://github.com/metal3-io/ironic-image/pull/429)
```suggestion
- Custom iPXE firmware building and deployment support [#429](https://github.com/metal3-io/ironic-image/pull/429)
```

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +| Reviewer/Approver  | GitHub ID      | Affiliation                    |
```suggestion
| Approver  | GitHub ID      | Affiliation                    |
```
All are approvers.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +| Andrea Fasano      | andfasano      | Red Hat                        |
Sort this by either name or company.

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +downloads from the Metal3's container repository from 11-12-2023 to
4 day period?

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +of TLS 1.3 only.
We're not mentioning TODO items here, only accomplishments. We don't mention plans for other content either. (We imply signing and other improvements by aiming to get higher openssf scorecard/clomonitor scores/CII badge etc.)

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +The Metal³ project believes in CNCF’s mission to make cloud-native technologies
```suggestion
The Metal3 project believes in CNCF’s mission to make cloud-native technologies
```

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +manage their applications, Metal³ aims to apply similar patterns such as
```suggestion
manage their applications, Metal3 aims to apply similar patterns such as
```

2023-12-19 14:18 UTC, tuminoid commented on proposals/incubation/metal3.md
> +Metal3-io's IPAM is also used by cluster-api-provider-vsphere's CI.
```suggestion
Metal3's IPAM is also used by cluster-api-provider-vsphere's CI. 
```

2023-12-19 14:43 UTC, kashifest commented on proposals/incubation/metal3.md
> +- Implemented support adding pre-provisining Network data for Ironic node [#1380](https://github.com/metal3-io/baremetal-operator/pull/1380)
1380 is already in the list

2023-12-19 14:58 UTC, Rozzii commented on proposals/incubation/metal3.md
> +Repositories that have proved to be unmaintainable or lost their importance have
IMO it is a common choice of words

2023-12-19 15:06 UTC, kashifest commented on proposals/incubation/metal3.md
> +- Discover your hardware inventory
firmware update ?

2023-12-19 15:30 UTC, kashifest commented on proposals/incubation/metal3.md
> +| Andrea Fasano      | andfasano      | Red Hat                        |
sorted by github id as in maintainers file

2023-12-19 15:31 UTC, kashifest commented on proposals/incubation/metal3.md
> +downloads from the Metal3's container repository from 11-12-2023 to
five :D , a week

2023-12-19 15:34 UTC, kashifest commented on proposals/incubation/metal3.md
> +
IMO its fine as is.

2023-12-20 06:17 UTC, tuminoid commented on proposals/incubation/metal3.md
> +| Andrea Fasano      | andfasano      | Red Hat                        |
It definitely is not. Here is the ALL OWNERS:

```yaml
approvers:
- andfasano
- bfournie
- derekhiggins
- dtantsur
- elfosardo
- furkatgofurov7
- honza
- hroyrh
- iurygregory
- kashifest
- lentzi90
- mboukhalfa
- Rozzii
- smoshiur1237
- tuminoid
- zaneb
```

2023-12-20 06:20 UTC, tuminoid commented on proposals/incubation/metal3.md
> +downloads from the Metal3's container repository from 11-12-2023 to
A week is such a random time period statistically. It could dip down or spike up massively for any reason. A month would be more legit IMO.

2023-12-20 08:07 UTC, kashifest commented on proposals/incubation/metal3.md
> +| Andrea Fasano      | andfasano      | Red Hat                        |
my bad, thanks a lot for catching it up, fixed.

2023-12-20 08:22 UTC, kashifest commented on proposals/incubation/metal3.md
> +downloads from the Metal3's container repository from 11-12-2023 to
Done

2023-12-20 10:44 UTC, kashifest commented
/close

2023-12-21 09:41 UTC, tuminoid commented
> /close

Prow is not configured for this. Closing manually.

2023-12-21 09:41 UTC, closed without merging